<a href="https://colab.research.google.com/github/Parry1J/AIBootCamp/blob/main/Exercise_PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import the __`torch`__ package

In [31]:
import torch as pt
pt.manual_seed(0);

import torch as pt1
pt1.manual_seed(0);


In [ ]:
pt.tensor

In [39]:
3*0.1


0.30000000000000004

## Create a vector of ten zeros

In [3]:
vector = pt.zeros(10)
vector

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [8]:
vector2 = pt.zeros(10)
vector2[4] = 1
vector2

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [14]:
vector3 = pt.arange(10,50)
vector3.view(-1,1)




tensor([[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49]])

## Reverse the previous vector

In [15]:
reversed(vector3)

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
# prompt: Create a 3x3 matrix with values ranging from 0 to 8

matrix = pt.arange(0,9).view(3,3)
matrix


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Find the indices of the non-zero elements of the following array:

In [17]:
v = pt.tensor([1, 2, 0, 0, 4, 0]) # Given
v = v.nonzero()
v

tensor([[0],
        [1],
        [4]])

## Create a 5x5 identity matrix

In [30]:

m = pt1.eye(5)
m


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Create a 3x3x3 array with random values

In [32]:
x = pt.rand(3,3,3)
x


tensor([[[0.4963, 0.7682, 0.0885],
         [0.1320, 0.3074, 0.6341],
         [0.4901, 0.8964, 0.4556]],

        [[0.6323, 0.3489, 0.4017],
         [0.0223, 0.1689, 0.2939],
         [0.5185, 0.6977, 0.8000]],

        [[0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742],
         [0.4194, 0.5529, 0.9527]]])

## Find the minimum and maximum values generated in the previous step

In [36]:
x.min().item(), x.max().item()


(0.022325754165649414, 0.9527381062507629)

## Create a vector with 30 random values and find its mean

In [38]:
x = pt.rand(30).mean()
x


tensor(0.5176)

## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [ ]:
x2 = pt.rand()

## Try to predict the output of each of the following cells before running them

In [ ]:
0 * float('nan')

In [ ]:
float('nan') == float('nan')

In [ ]:
float('inf') > float('nan')

In [ ]:
float('nan') - float('nan')

In [ ]:
0.3 == 3 * 0.1

In [ ]:
pt.tensor([0]) // pt.tensor([0]) #crashes the kernel :) continue with the next cell

In [ ]:
import torch as pt #this is in case you crashed on the previous cell
pt.tensor([0]) // pt.tensor([0.0])

In [ ]:
nan_scalar = pt.tensor([float('nan')])

pt.isnan(nan_scalar)

In [ ]:
pt.tensor([0]) / pt.tensor([0.0])

## Find the integer part of the following array using four different methods:

In [ ]:
a = pt.randn((10,), dtype = pt.float32)
a

## Create a vector of 10 values from 0 to 1, both included

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

## Subtract the mean of each row of the following matrix

In [ ]:
m = pt.rand(3, 3)
m

## Add 1,000,000 numbers together using __`torch`__ vectorized operations

## Create a 4x4 array of the first 16 powers of 3

Copyright 2021 CounterFactual.AI LLC. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.